

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU1NQW9HQTFVRUF3d0RZbTlpTVJBd0RnWURWUVFLREFkc1pXRnlibVZ5TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNmtvNXJrNVU2eXBnWnJCekZheEtNRC9HCnBONEt5SzgyTStJZzBLVzJzb0V1ajZIUnhNb2dNbWYrYlNCTThibFIwQjd6UGc1ME1GamJGZFl6MUJRL0x5MHIKdUdidTVXcHFuSjBaUmlpR3EzQzFaUEt5bXdnQXBrTmN6VGVVckNFN3hYOGxSL0tubFFDT1dqRVlHRy9ldlY0MQpUMWxYbEFpdXhqanV0RDN0UE5hNVJ5YUdTeFh4bmdlOFV4Mk1wdjU3RmpKOGEveDNkZllkcVZpbXRkR214d3dHCjd6Q2xHZnl4SDlXaUU1NDNsNVNCVDdDamM5K2NJSFBEVk80V24xNVFaUllQVW41NXhiZk9xTnhSSEwzeWNDb3YKQlFRdFNzUVI2czlacllkRVlINnM4Yk0rMmwzWTlNK0VoOE5EaTRibWxoakF0ajNRU0hZMFpLS245VkY0Q1FJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJUVZKMUtMMjVobE9wYVlJVkRCc0dHK1MzTFVwTUptCktySEJhUE9TV1ZzRVU1MitJcS9ocmI0Rnd1U1pnM3RMNjd1OXlDRk1ZZHkwOWw4YkdaV3AzNENSYzJKUGFtL2kKU3VsdW80dUgvUG1RUk1TSjc0Y3hOYnVlSzlUTkJCejdISFJMUTdQL3k3S2hrS0VqQkdSMGs0b2J1bG9JaWZsagpVWDk5SzluQmZFa0UveWJDMm5CWE1GZWhVUEtSdi9ZOE11and3eFkrUkNPMHY2cmhBSHFleXdCSXdoMDhOMTByCnN3d0RYeldpbzBOd24veTh4c0NZbmpSNXliRnJYS2hUSUJaQ1VBRSsxdndidmZjNWNycWxrcy9vL01tSjBKQUMKVnBYa2x2VjQ5OU5DRnFiUGdnZUNmc3RrQnR1cCtDWkpLSzE3NHRYV3NMUkJTRnplWiszaXhRYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth

